import {
  Landmark,
  Receipt,
  Calculator,
  ShieldCheck,
  Building2,
  FileText,
  TrendingUp,
  Wallet,
  Users,
  Rocket,
  Globe,
  Briefcase,
  BarChart3,
  ClipboardCheck,
  Handshake,
  Factory,
  ShoppingCart,
  Store,
  Laptop,
  Home,
  HeartPulse,
  Ship,
  UserCheck,
  MessageCircle,
  Clock,
  Lock,
  Compass,
  Lightbulb,
  Award,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  landmark: Landmark,
  receipt: Receipt,
  calculator: Calculator,
  "shield-check": ShieldCheck,
  building: Building2,
  "file-text": FileText,
  "trending-up": TrendingUp,
  wallet: Wallet,
  users: Users,
  rocket: Rocket,
  globe: Globe,
  briefcase: Briefcase,
  "bar-chart": BarChart3,
  "clipboard-check": ClipboardCheck,
  handshake: Handshake,
  factory: Factory,
  "shopping-cart": ShoppingCart,
  store: Store,
  laptop: Laptop,
  home: Home,
  "heart-pulse": HeartPulse,
  ship: Ship,
  "user-check": UserCheck,
  "message-circle": MessageCircle,
  clock: Clock,
  lock: Lock,
  compass: Compass,
  lightbulb: Lightbulb,
  award: Award,
};

export const ICON_NAMES = Object.keys(ICONS);

export function getIcon(name?: string | null, fallback: LucideIcon = Landmark): LucideIcon {
  if (!name) return fallback;
  return ICONS[name] ?? fallback;
}
